# most personal metadata can be found in ./resume.json

- description: Portfolio of web &amp; ui designer/developer hybrid Doris Warren.
  img: ../src/images/butterfly.png

  availability:
    status: false
    available: '  🦋 Available for new projects. <a href="mailto:doriswarren11@gmail.com">Let’s talk</a>!'
    unavailable: Not available for new projects.

  # Footer actions
  gpg: https://kretschmann.io/pub.gpg
  addressbook:  /matthias-kretschmann.vcf

  typekitID: dtg3zui

  # Analytics tools
  matomoUrl: https://analytics.kremalicious.com
  matomoSite: 2

  allowedHosts:
    - matthiaskretschmann.com
    - beta.matthiaskretschmann.com
    - localhost
