# most personal metadata can be found in ./resume.json

- description: Portfolio of web &amp; ui designer/developer hybrid Doris Warren.
  img: ../src/images/butterfly.png

  availability:
    status: false
    available: '  🦋 Available for new projects. <a href="mailto:doriswarren11@gmail.com">Let’s talk</a>!'
    unavailable: Not available for new projects.




  typekitID: dtg3zui



  allowedHosts:
    - localhost
